[Settings]
  ID = "8b263af1-4dbd-4234-9efb-da900e03cc77"

[Build]
  Publish = ""
  Functions = ""

[[redirects]]
  from = "http://acafaf-505606015.netlify.com/*"
  to = "http://andrewhudson.me/:splat"
  status = 301
